# https://taskfile.dev
version: '3'

silent: true

vars:
  DOCKER_COMPOSE_FILES: |-
    docker-compose.yml
    docker-compose.sentry.yml
  DOCKER_COMPOSE_CMD: |-
    docker compose {{range $file := .DOCKER_COMPOSE_FILES | splitLines -}} -f ./deploy/local/{{$file}} {{end}}

  GO_MODULE: github.com/ekhvalov/bank-chat-service
  GO_FILES:
    sh: find . -type f -name '*.go' -not -path "./vendor/*" -not -path "*.gen.go" | tr "\n" " "

  GOLANGCI_LINT_VERSION: "1.54.2"
  GOLANGCI_LINT_URL: "https://github.com/golangci/golangci-lint/releases/download/v{{.GOLANGCI_LINT_VERSION}}"
  GOLANGCI_LINT_DIR: "golangci-lint-{{.GOLANGCI_LINT_VERSION}}-{{OS}}-amd64"
  GOLANGCI_LINT_ARCHIVE_FILE: "{{.GOLANGCI_LINT_DIR}}.tar.gz"
  GOLANGCI_LINT_CHECKSUMS_FILE: "golangci-lint-{{.GOLANGCI_LINT_VERSION}}-checksums.txt"

  TOOLS_DIR:
    sh: echo "$(pwd)/tools/bin"

  TYPES: |
    ChatID
    MessageID
    ProblemID
    UserID
  TYPES_PKG: types
  TYPES_DST: ./internal/types/types.gen.go

env:
  COMPOSE_PROJECT_NAME: bankchat

tasks:
  default:
    cmds:
      - task: tidy
      - task: fmt
      - task: lint
      - task: tests
      - task: build

  deps:
    cmds:
      - "{{.DOCKER_COMPOSE_CMD}} up -d"

  deps:cmd:
    cmds:
      - "{{.DOCKER_COMPOSE_CMD}} {{.CLI_ARGS}}"

  deps:status:
    cmds:
      - "{{.DOCKER_COMPOSE_CMD}} ps -a"

  deps:logs:
    cmds:
      - "{{.DOCKER_COMPOSE_CMD}} logs {{.CLI_ARGS}}"

  deps:stop:
    cmds:
      - "{{.DOCKER_COMPOSE_CMD}} stop"

  deps:reset-psql:
    cmds:
      - task: deps:reset
        vars:
          SERVICE: postgres

  deps:reset:
    cmds:
      - "{{.DOCKER_COMPOSE_CMD}} rm -fsv {{.SERVICE}}"
      - "{{.DOCKER_COMPOSE_CMD}} up -d {{.SERVICE}}"

  deps:sentry-key:
    dir: ./deploy/local # TODO: duplication
    cmds:
      - 'echo "SENTRY_SECRET_KEY=\"{{.SENTRY_KEY}}\"" >> .env'
    vars:
      SENTRY_KEY:
        sh: docker run --rm --quiet sentry:9.1.2 config generate-secret-key
    status:
      - test -f .env
      - grep SENTRY_SECRET_KEY .env

  tidy:
    - echo "- Tidy"
    - go mod tidy
    - task: vendor

  vendor:
    - echo "- Vendor"
    - go mod vendor

  fmt:
    - echo "- Format"
    - "{{.TOOLS_DIR}}/gofumpt -w {{.GO_FILES}}"
    - "{{.TOOLS_DIR}}/gci write {{.GO_FILES}} --custom-order -s standard -s default -s Prefix\\({{.GO_MODULE}}\\)"

  lint:
    cmds:
      - echo "- Lint"
      - task: lint:cmd
        vars: { CLI_ARGS: "run -v --fix --timeout=5m ./..." }

  lint:cmd:
    cmds:
      - "{{.TOOLS_DIR}}/golangci-lint run -v --fix --timeout=5m ./..."

  tests:
    cmds:
      - echo "- Tests"
      - go test -race ./...

  build:
    cmds:
      - echo "- Build"
      - go build ./cmd/chat-service

  generate:
    cmds:
      - 'PATH="{{.TOOLS_DIR}}:$PATH" go generate {{.GO_MODULE}}/internal/logger'
      - 'PATH="{{.TOOLS_DIR}}:$PATH" go generate {{.GO_MODULE}}/internal/server-debug'
      - task: gen:types

  gen:types:
    cmds:
      - echo "Generate types..."
      - go run ./cmd/gen-types types ChatID,MessageID ./internal/types/types.gen.go

  dev-tools:install:
    vars:
      DEV_TOOLS: |
        github.com/daixiang0/gci@v0.11.2
        github.com/kazhuravlev/options-gen/cmd/options-gen@v0.30.0
        mvdan.cc/gofumpt@v0.5.0
    cmds:
      - echo "- Install dev tools"
      - mkdir -p "{{.TOOLS_DIR}}"
      - for: { var: DEV_TOOLS }
        cmd: GOBIN="{{.TOOLS_DIR}}" go install "{{ .ITEM }}"
      - task: golangci:install

  golangci:install:
    dir: "{{.TOOLS_DIR}}"
    cmds:
      - wget -q "{{.GOLANGCI_LINT_URL}}/{{.GOLANGCI_LINT_ARCHIVE_FILE}}"
      - wget -q "{{.GOLANGCI_LINT_URL}}/{{.GOLANGCI_LINT_CHECKSUMS_FILE}}"
      - grep "$(sha256sum {{.GOLANGCI_LINT_ARCHIVE_FILE}})" "{{.GOLANGCI_LINT_CHECKSUMS_FILE}}" > /dev/null
      - tar xf "{{.GOLANGCI_LINT_ARCHIVE_FILE}}" --strip-components 1 "{{.GOLANGCI_LINT_DIR}}/golangci-lint"
      - rm -f "{{.GOLANGCI_LINT_ARCHIVE_FILE}}" "{{.GOLANGCI_LINT_CHECKSUMS_FILE}}"
    status:
      - test -f "golangci-lint"
