// Package clientevents provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.15.0 DO NOT EDIT.
package clientevents

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/ekhvalov/bank-chat-service/internal/types"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// Defines values for EventType.
const (
	EventTypeMessageBlockedEvent EventType = "MessageBlockedEvent"
	EventTypeMessageSentEvent    EventType = "MessageSentEvent"
	EventTypeNewMessageEvent     EventType = "NewMessageEvent"
)

// AuthorID defines model for AuthorID.
type AuthorID = types.UserID

// Event defines model for Event.
type Event struct {
	union json.RawMessage
}

// ID defines model for EventID.
type ID = types.EventID

// EventType defines model for EventType.
type EventType string

// MessageBlockedEvent defines model for MessageBlockedEvent.
type MessageBlockedEvent struct {
	ID        ID        `json:"eventId"`
	EventType string    `json:"eventType"`
	MessageID MessageID `json:"messageId"`
	RequestID RequestID `json:"requestId"`
}

// MessageID defines model for MessageID.
type MessageID = types.MessageID

// MessageSentEvent defines model for MessageSentEvent.
type MessageSentEvent struct {
	ID        ID        `json:"eventId"`
	EventType string    `json:"eventType"`
	MessageID MessageID `json:"messageId"`
	RequestID RequestID `json:"requestId"`
}

// NewMessageEvent defines model for NewMessageEvent.
type NewMessageEvent struct {
	AuthorID  *AuthorID `json:"authorId,omitempty"`
	Body      string    `json:"body"`
	CreatedAt time.Time `json:"createdAt"`
	ID        ID        `json:"eventId"`
	EventType string    `json:"eventType"`
	IsService bool      `json:"isService"`
	MessageID MessageID `json:"messageId"`
	RequestID RequestID `json:"requestId"`
}

// RequestID defines model for RequestID.
type RequestID = types.RequestID

// AsNewMessageEvent returns the union data inside the Event as a NewMessageEvent
func (t Event) AsNewMessageEvent() (NewMessageEvent, error) {
	var body NewMessageEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromNewMessageEvent overwrites any union data inside the Event as the provided NewMessageEvent
func (t *Event) FromNewMessageEvent(v NewMessageEvent) error {
	v.EventType = "NewMessageEvent"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeNewMessageEvent performs a merge with any union data inside the Event, using the provided NewMessageEvent
func (t *Event) MergeNewMessageEvent(v NewMessageEvent) error {
	v.EventType = "NewMessageEvent"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(t.union, b)
	t.union = merged
	return err
}

// AsMessageSentEvent returns the union data inside the Event as a MessageSentEvent
func (t Event) AsMessageSentEvent() (MessageSentEvent, error) {
	var body MessageSentEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMessageSentEvent overwrites any union data inside the Event as the provided MessageSentEvent
func (t *Event) FromMessageSentEvent(v MessageSentEvent) error {
	v.EventType = "MessageSentEvent"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeMessageSentEvent performs a merge with any union data inside the Event, using the provided MessageSentEvent
func (t *Event) MergeMessageSentEvent(v MessageSentEvent) error {
	v.EventType = "MessageSentEvent"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(t.union, b)
	t.union = merged
	return err
}

// AsMessageBlockedEvent returns the union data inside the Event as a MessageBlockedEvent
func (t Event) AsMessageBlockedEvent() (MessageBlockedEvent, error) {
	var body MessageBlockedEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMessageBlockedEvent overwrites any union data inside the Event as the provided MessageBlockedEvent
func (t *Event) FromMessageBlockedEvent(v MessageBlockedEvent) error {
	v.EventType = "MessageBlockedEvent"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeMessageBlockedEvent performs a merge with any union data inside the Event, using the provided MessageBlockedEvent
func (t *Event) MergeMessageBlockedEvent(v MessageBlockedEvent) error {
	v.EventType = "MessageBlockedEvent"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(t.union, b)
	t.union = merged
	return err
}

func (t Event) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"eventType"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t Event) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "MessageBlockedEvent":
		return t.AsMessageBlockedEvent()
	case "MessageSentEvent":
		return t.AsMessageSentEvent()
	case "NewMessageEvent":
		return t.AsNewMessageEvent()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t Event) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *Event) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xWPW/bMBD9K8K1QBfZctIl4JYvFEHRBKjbKfBAS2eJtUSqvJPcwNB/L0jJsWyrSQy4",
	"Q4FOIsj7fO+dyDXEpiiNRs0EYg0UZ1hIv7ysODP27satF8YWkkFAVakEQuCnEkEAsVU6hRB+jVIz0rJw",
	"m89+3XZn6z40/k64dzRSRWksuyyl5AwEpIqzaj6OTRHhMqtlbupoLvVyFGeSR4S2VjFGSjNaLfPIB4am",
	"CeG2Ru0DJYpiqwqlJRvrI1tTouWn+7ZEdIbfXF1NCEbjwwLE4xreW1yAgHfRFpOoAyS6x9UXJJIptlma",
	"8GX7zniKmo9yuMpNvMSk85ltujqehj8QsIn2FxnwwIo1oK4KEI+wD10IB+A8b+20P9vvsBm22xKs0EvX",
	"83uXuOVLkG+waMKeIsT6MGnRJn09YlddG9PizwrpDXV87QxvPIbOTVlMHHSbRvol9AP3C59t0TleLVvH",
	"IdEMnp5QNgd6+M/ohtH94TlARra/21dLev4tNyHMTfI0CEtsUTIml7yjn0QyjlgVCAMDeWpmFE1bofRO",
	"58bkKPU/Q1yHcB/PfmOO122iIyd16zg0qYOnJ5tUh4nSC+OpUZy7vFdSL4NpVboMwXUmObjOFWoOPOME",
	"IdRoSRkNAuozf+GWqGWpQMDH8dl4AqGvyos5Iq7mbpFie5Gju8hLbt3vOKgIKVgYG6So0UpWOg087jQO",
	"HjhDu1KEgeIgMUj6A4/B53OWRjv64RPy1CVx3FFpNLVjdD6ZuE9sNHdjJssyV7F3jH6QK2DzPHqT1sGj",
	"tdvAw2cPYhOCgxgt+WfHrs0N1pibsnAQtlYQQmVzELAiEUW5iWWeGWJxMbmYRCvyL4vdGLfnt/u+3nDW",
	"/A4AAP//jne/sPAJAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
