version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: chat-service
      POSTGRES_USER: chat-service
      POSTGRES_PASSWORD: chat-service
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.4
    depends_on:
      - postgres
    command:
      - start-dev --import-realm
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_SCHEMA: public
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./keycloak-Bank-realm.json:/opt/keycloak/data/import/bank-realm.json

  zookeeper:
    image: zookeeper:3.8.0

  kafka:
    image: wurstmeister/kafka:2.13-2.8.1
    hostname: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://kafka:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "chat.messages:16:1"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"

  client:
    image: golang:1.20.4
    depends_on:
      - kafka
      - postgres
      - keycloak
    volumes:
      - ../../:/src
    working_dir: /src
    command: go run ./cmd/chat-service -config ./configs/config.e2e.toml

  tester:
    image: golang:1.20.4
    depends_on:
      - client
    volumes:
      - ../../:/src
    working_dir: /src
    environment:
      E2E_CLIENT_V1_API_ENDPOINT: "http://client:8080/v1"
      E2E_KEYCLOAK_BASE_PATH: "http://keycloak:8080"
      E2E_KEYCLOAK_REALM: "Bank"
      E2E_KEYCLOAK_CLIENT_ID: "e2e-testing"
      E2E_KEYCLOAK_CLIENT_SECRET: "hVjoxHeYBMJ9pGhXYuUUgIzJ8rEhicsv"
      E2E_KEYCLOAK_CLIENT_DEBUG: "false"
      E2E_KEYCLOAK_CLIENTS: "e2e_client_0,e2e_client_1"
    command: /src/tools/bin/ginkgo --fail-fast --timeout=1m --tags e2e ./tests/e2e
