// Code generated by MockGen. DO NOT EDIT.
// Source: job.go
//
// Generated by this command:
//
//	mockgen -source=job.go -destination=mocks/job_mock.gen.go -typed -package=managerassignedtoproblemjobmocks
//
// Package managerassignedtoproblemjobmocks is a generated GoMock package.
package managerassignedtoproblemjobmocks

import (
	context "context"
	reflect "reflect"

	messagesrepo "github.com/ekhvalov/bank-chat-service/internal/repositories/messages"
	problemsrepo "github.com/ekhvalov/bank-chat-service/internal/repositories/problems"
	eventstream "github.com/ekhvalov/bank-chat-service/internal/services/event-stream"
	types "github.com/ekhvalov/bank-chat-service/internal/types"
	gomock "go.uber.org/mock/gomock"
)

// MockproblemRepository is a mock of problemRepository interface.
type MockproblemRepository struct {
	ctrl     *gomock.Controller
	recorder *MockproblemRepositoryMockRecorder
}

// MockproblemRepositoryMockRecorder is the mock recorder for MockproblemRepository.
type MockproblemRepositoryMockRecorder struct {
	mock *MockproblemRepository
}

// NewMockproblemRepository creates a new mock instance.
func NewMockproblemRepository(ctrl *gomock.Controller) *MockproblemRepository {
	mock := &MockproblemRepository{ctrl: ctrl}
	mock.recorder = &MockproblemRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockproblemRepository) EXPECT() *MockproblemRepositoryMockRecorder {
	return m.recorder
}

// GetProblemByID mocks base method.
func (m *MockproblemRepository) GetProblemByID(ctx context.Context, problemID types.ProblemID) (*problemsrepo.Problem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProblemByID", ctx, problemID)
	ret0, _ := ret[0].(*problemsrepo.Problem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProblemByID indicates an expected call of GetProblemByID.
func (mr *MockproblemRepositoryMockRecorder) GetProblemByID(ctx, problemID any) *problemRepositoryGetProblemByIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProblemByID", reflect.TypeOf((*MockproblemRepository)(nil).GetProblemByID), ctx, problemID)
	return &problemRepositoryGetProblemByIDCall{Call: call}
}

// problemRepositoryGetProblemByIDCall wrap *gomock.Call
type problemRepositoryGetProblemByIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *problemRepositoryGetProblemByIDCall) Return(arg0 *problemsrepo.Problem, arg1 error) *problemRepositoryGetProblemByIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *problemRepositoryGetProblemByIDCall) Do(f func(context.Context, types.ProblemID) (*problemsrepo.Problem, error)) *problemRepositoryGetProblemByIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *problemRepositoryGetProblemByIDCall) DoAndReturn(f func(context.Context, types.ProblemID) (*problemsrepo.Problem, error)) *problemRepositoryGetProblemByIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockmessageRepository is a mock of messageRepository interface.
type MockmessageRepository struct {
	ctrl     *gomock.Controller
	recorder *MockmessageRepositoryMockRecorder
}

// MockmessageRepositoryMockRecorder is the mock recorder for MockmessageRepository.
type MockmessageRepositoryMockRecorder struct {
	mock *MockmessageRepository
}

// NewMockmessageRepository creates a new mock instance.
func NewMockmessageRepository(ctrl *gomock.Controller) *MockmessageRepository {
	mock := &MockmessageRepository{ctrl: ctrl}
	mock.recorder = &MockmessageRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockmessageRepository) EXPECT() *MockmessageRepositoryMockRecorder {
	return m.recorder
}

// GetMessageByID mocks base method.
func (m *MockmessageRepository) GetMessageByID(ctx context.Context, msgID types.MessageID) (*messagesrepo.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessageByID", ctx, msgID)
	ret0, _ := ret[0].(*messagesrepo.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessageByID indicates an expected call of GetMessageByID.
func (mr *MockmessageRepositoryMockRecorder) GetMessageByID(ctx, msgID any) *messageRepositoryGetMessageByIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessageByID", reflect.TypeOf((*MockmessageRepository)(nil).GetMessageByID), ctx, msgID)
	return &messageRepositoryGetMessageByIDCall{Call: call}
}

// messageRepositoryGetMessageByIDCall wrap *gomock.Call
type messageRepositoryGetMessageByIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *messageRepositoryGetMessageByIDCall) Return(arg0 *messagesrepo.Message, arg1 error) *messageRepositoryGetMessageByIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *messageRepositoryGetMessageByIDCall) Do(f func(context.Context, types.MessageID) (*messagesrepo.Message, error)) *messageRepositoryGetMessageByIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *messageRepositoryGetMessageByIDCall) DoAndReturn(f func(context.Context, types.MessageID) (*messagesrepo.Message, error)) *messageRepositoryGetMessageByIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockmanagerLoadService is a mock of managerLoadService interface.
type MockmanagerLoadService struct {
	ctrl     *gomock.Controller
	recorder *MockmanagerLoadServiceMockRecorder
}

// MockmanagerLoadServiceMockRecorder is the mock recorder for MockmanagerLoadService.
type MockmanagerLoadServiceMockRecorder struct {
	mock *MockmanagerLoadService
}

// NewMockmanagerLoadService creates a new mock instance.
func NewMockmanagerLoadService(ctrl *gomock.Controller) *MockmanagerLoadService {
	mock := &MockmanagerLoadService{ctrl: ctrl}
	mock.recorder = &MockmanagerLoadServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockmanagerLoadService) EXPECT() *MockmanagerLoadServiceMockRecorder {
	return m.recorder
}

// CanManagerTakeProblem mocks base method.
func (m *MockmanagerLoadService) CanManagerTakeProblem(ctx context.Context, managerID types.UserID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CanManagerTakeProblem", ctx, managerID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CanManagerTakeProblem indicates an expected call of CanManagerTakeProblem.
func (mr *MockmanagerLoadServiceMockRecorder) CanManagerTakeProblem(ctx, managerID any) *managerLoadServiceCanManagerTakeProblemCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanManagerTakeProblem", reflect.TypeOf((*MockmanagerLoadService)(nil).CanManagerTakeProblem), ctx, managerID)
	return &managerLoadServiceCanManagerTakeProblemCall{Call: call}
}

// managerLoadServiceCanManagerTakeProblemCall wrap *gomock.Call
type managerLoadServiceCanManagerTakeProblemCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *managerLoadServiceCanManagerTakeProblemCall) Return(arg0 bool, arg1 error) *managerLoadServiceCanManagerTakeProblemCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *managerLoadServiceCanManagerTakeProblemCall) Do(f func(context.Context, types.UserID) (bool, error)) *managerLoadServiceCanManagerTakeProblemCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *managerLoadServiceCanManagerTakeProblemCall) DoAndReturn(f func(context.Context, types.UserID) (bool, error)) *managerLoadServiceCanManagerTakeProblemCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockeventStream is a mock of eventStream interface.
type MockeventStream struct {
	ctrl     *gomock.Controller
	recorder *MockeventStreamMockRecorder
}

// MockeventStreamMockRecorder is the mock recorder for MockeventStream.
type MockeventStreamMockRecorder struct {
	mock *MockeventStream
}

// NewMockeventStream creates a new mock instance.
func NewMockeventStream(ctrl *gomock.Controller) *MockeventStream {
	mock := &MockeventStream{ctrl: ctrl}
	mock.recorder = &MockeventStreamMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockeventStream) EXPECT() *MockeventStreamMockRecorder {
	return m.recorder
}

// Publish mocks base method.
func (m *MockeventStream) Publish(ctx context.Context, userID types.UserID, event eventstream.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, userID, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockeventStreamMockRecorder) Publish(ctx, userID, event any) *eventStreamPublishCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockeventStream)(nil).Publish), ctx, userID, event)
	return &eventStreamPublishCall{Call: call}
}

// eventStreamPublishCall wrap *gomock.Call
type eventStreamPublishCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *eventStreamPublishCall) Return(arg0 error) *eventStreamPublishCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *eventStreamPublishCall) Do(f func(context.Context, types.UserID, eventstream.Event) error) *eventStreamPublishCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *eventStreamPublishCall) DoAndReturn(f func(context.Context, types.UserID, eventstream.Event) error) *eventStreamPublishCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
