// Code generated by ent, DO NOT EDIT.

package store

import (
	"time"

	"github.com/ekhvalov/bank-chat-service/internal/store/chat"
	"github.com/ekhvalov/bank-chat-service/internal/store/message"
	"github.com/ekhvalov/bank-chat-service/internal/store/problem"
	"github.com/ekhvalov/bank-chat-service/internal/store/schema"
	"github.com/ekhvalov/bank-chat-service/internal/types"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	chatFields := schema.Chat{}.Fields()
	_ = chatFields
	// chatDescCreatedAt is the schema descriptor for created_at field.
	chatDescCreatedAt := chatFields[2].Descriptor()
	// chat.DefaultCreatedAt holds the default value on creation for the created_at field.
	chat.DefaultCreatedAt = chatDescCreatedAt.Default.(func() time.Time)
	// chatDescID is the schema descriptor for id field.
	chatDescID := chatFields[0].Descriptor()
	// chat.DefaultID holds the default value on creation for the id field.
	chat.DefaultID = chatDescID.Default.(func() types.ChatID)
	messageFields := schema.Message{}.Fields()
	_ = messageFields
	// messageDescIsVisibleForClient is the schema descriptor for is_visible_for_client field.
	messageDescIsVisibleForClient := messageFields[2].Descriptor()
	// message.DefaultIsVisibleForClient holds the default value on creation for the is_visible_for_client field.
	message.DefaultIsVisibleForClient = messageDescIsVisibleForClient.Default.(bool)
	// messageDescIsVisibleForManager is the schema descriptor for is_visible_for_manager field.
	messageDescIsVisibleForManager := messageFields[3].Descriptor()
	// message.DefaultIsVisibleForManager holds the default value on creation for the is_visible_for_manager field.
	message.DefaultIsVisibleForManager = messageDescIsVisibleForManager.Default.(bool)
	// messageDescBody is the schema descriptor for body field.
	messageDescBody := messageFields[4].Descriptor()
	// message.BodyValidator is a validator for the "body" field. It is called by the builders before save.
	message.BodyValidator = messageDescBody.Validators[0].(func(string) error)
	// messageDescCheckedAt is the schema descriptor for checked_at field.
	messageDescCheckedAt := messageFields[5].Descriptor()
	// message.DefaultCheckedAt holds the default value on creation for the checked_at field.
	message.DefaultCheckedAt = messageDescCheckedAt.Default.(func() time.Time)
	// messageDescCreatedAt is the schema descriptor for created_at field.
	messageDescCreatedAt := messageFields[8].Descriptor()
	// message.DefaultCreatedAt holds the default value on creation for the created_at field.
	message.DefaultCreatedAt = messageDescCreatedAt.Default.(func() time.Time)
	// messageDescID is the schema descriptor for id field.
	messageDescID := messageFields[0].Descriptor()
	// message.DefaultID holds the default value on creation for the id field.
	message.DefaultID = messageDescID.Default.(func() types.MessageID)
	problemFields := schema.Problem{}.Fields()
	_ = problemFields
	// problemDescResolvedAt is the schema descriptor for resolved_at field.
	problemDescResolvedAt := problemFields[2].Descriptor()
	// problem.DefaultResolvedAt holds the default value on creation for the resolved_at field.
	problem.DefaultResolvedAt = problemDescResolvedAt.Default.(func() time.Time)
	// problemDescCreatedAt is the schema descriptor for created_at field.
	problemDescCreatedAt := problemFields[3].Descriptor()
	// problem.DefaultCreatedAt holds the default value on creation for the created_at field.
	problem.DefaultCreatedAt = problemDescCreatedAt.Default.(func() time.Time)
	// problemDescID is the schema descriptor for id field.
	problemDescID := problemFields[0].Descriptor()
	// problem.DefaultID holds the default value on creation for the id field.
	problem.DefaultID = problemDescID.Default.(func() types.ProblemID)
}
