[global]
env = "prod"

[log]
level = "warn"

[clients]
[clients.keycloak]
base_path = "http://keycloak:8080"
realm = "Bank"
client_id = "e2e-testing"
client_secret = "hVjoxHeYBMJ9pGhXYuUUgIzJ8rEhicsv"
debug_mode = false
[clients.postgres]
address = "postgres:5432"
username = "chat-service"
password = "chat-service"
database = "chat-service"
debug_mode = false

[servers]
[servers.debug]
addr = ":8079"

[servers.client]
addr = ":8080"
allow_origins = ["http://localhost:3011", "http://localhost:3000"]
[servers.client.required_access]
resource = "e2e-testing"
role = "support-chat-client"

[services]
[services.msg_producer]
brokers = ["kafka:9092"]
topic = "chat.messages"
batch_size = 1
encrypt_key = "" # Leave it blank to disable encryption.
#encrypt_key = "68566D597133743677397A2443264629"

[services.outbox]
workers = 2
idle_time = "1s"
reserve_for = "5m"

[sentry]
#dsn = "http://3ec334f6b3024abe8c9355b8986ce0cf@sentry.localhost:9000/2"
dsn = ""
