[global]
env = "dev"

[log]
level = "debug"

[clients]
[clients.keycloak]
base_path = "http://keycloak:8080"
realm = "Bank"
client_id = "e2e-testing"
client_secret = "hVjoxHeYBMJ9pGhXYuUUgIzJ8rEhicsv"
debug_mode = false

[clients.postgres]
address = "postgres:5432"
username = "chat-service"
password = "chat-service"
database = "chat-service"
debug_mode = false

[servers]
[servers.debug]
addr = ":8079"

[servers.client]
addr = ":8080"
allow_origins = ["http://localhost:3011", "http://localhost:3000"]
sec_ws_protocol = "chat-service-protocol"
[servers.client.required_access]
resource = "e2e-testing"
role = "support-chat-client"

[servers.manager]
addr = ":8081"
allow_origins = ["http://localhost:3011", "http://localhost:3001"]
sec_ws_protocol = "chat-service-protocol"
[servers.manager.required_access]
resource = "chat-ui-manager"
role = "support-chat-manager"

[services]
[services.afc_verdicts_processor]
brokers = ["kafka:9092"]
consumers = 1
consumer_group = "consumerGroup"
verdicts_topic = "afc.msg-verdicts"
verdicts_dlq_topic = "afc.msg-verdicts.dlq"
#verdicts_signing_public_key = ""
verdicts_signing_public_key = """
-----BEGIN PUBLIC KEY-----
MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDrjvZ8ssagjMihwtlt11EpXlmm
l3xsd9gVLnpEps290Piv3equ05rUW3dYBOgeS297logZjUeiyB1G3ELMT1po9Po3
pNMng4fmkFo7iIpBGAtrhRn8WuEUE7oHNZgin8B/e7fpktyximSburB+w+M6eUT7
snjKph25tjCV2y7ZvQIDAQAB
-----END PUBLIC KEY-----
"""

[services.manager_load]
max_problems_at_same_time = 5

[services.manager_scheduler]
idle_duration = "300ms"

[services.msg_producer]
brokers = ["kafka:9092"]
topic = "chat.messages"
batch_size = 1
#encrypt_key = "" # Leave it blank to disable encryption.
encrypt_key = "68566D597133743677397A2443264629"

[services.outbox]
workers = 2
idle_time = "1s"
reserve_for = "5m"

[sentry]
#dsn = "http://3ec334f6b3024abe8c9355b8986ce0cf@sentry.localhost:9000/2"
dsn = ""
