[global]
env = "dev"

[log]
level = "info"

[clients]
[clients.keycloak]
base_path = "http://localhost:3010"
realm = "Bank"
client_id = "chat-service"
client_secret = "some-secret"
debug_mode = false
[clients.postgres]
address = "localhost:5432"
username = "chat-service"
password = "chat-service"
database = "chat-service"
debug_mode = true

[servers]
[servers.debug]
addr = ":8079"

[servers.client]
addr = ":8080"
allow_origins = ["http://localhost:3011", "http://localhost:3000"]
[servers.client.required_access]
resource = "chat-ui-client"
role = "support-chat-client"

[sentry]
#dsn = "http://3ec334f6b3024abe8c9355b8986ce0cf@sentry.localhost:9000/2"
dsn = ""
