// Code generated by options-gen. DO NOT EDIT.
package canreceiveproblems

import (
	fmt461e464ebed9 "fmt"

	errors461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/errors"
	validator461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/validator"
)

type OptOptionsSetter func(o *Options)

func NewOptions(
	loadService managerLoadService,
	pool managerPool,
	options ...OptOptionsSetter,
) Options {
	o := Options{}

	// Setting defaults from field tag (if present)

	o.loadService = loadService
	o.pool = pool

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func (o *Options) Validate() error {
	errs := new(errors461e464ebed9.ValidationErrors)
	errs.Add(errors461e464ebed9.NewValidationError("loadService", _validate_Options_loadService(o)))
	errs.Add(errors461e464ebed9.NewValidationError("pool", _validate_Options_pool(o)))
	return errs.AsError()
}

func _validate_Options_loadService(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.loadService, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `loadService` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_pool(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.pool, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `pool` did not pass the test: %w", err)
	}
	return nil
}
